title: Applied Data Intelligence
description: Applied Data Intelligence Group, Faculty of Medicine, Prince of Songkla University
google_analytics:
theme: jekyll-theme-midnight
encoding: utf-8
markdown: kramdown
